### ISSUE TITLE
[Suggestion] More Windows MinGW instructions for compiling a .lib

### ISSUE THREAD

**Issue by DBraun** [thestk/stk#101]
Thank you for the examples/*.vcxproj files. I was able to get a custom project built. However, for convenience, I'd like to build a .lib for Windows.

I've installed MinGW. I have `C:\MinGW\bin\autoconf`.  If I launch a MinGW 64 prompt, cd to the stk directory, and type `autoconf` I get `bash: autoconf: command not found`. If I type `C:/MinGW/bin/autoconf` I get `C:/MinGW/bin/autoconf-2.68: line 501: /mingw/bin/autom4te-2.68: No such file or directory`.

I also have `C:\MinGW\share\autoconf\autoconf` but am not sure what good it is.

I would really appreciate a few more troubleshooting steps for the Windows installation. Thank you!

**Comment by garyscavone** [comment]
Seems like a path setup issue in your shell … are you using MSYS?

But you could also download the distribution from

- https://ccrma.stanford.edu/software/stk/download.html

which contains a configure script.

**Comment by DBraun** [comment]
Thanks.

I did `C:/Program Files/Git/bin/sh ./configure --disable-realtime`
Then `C:\MinGW\bin\mingw32-make.exe`
I had to go to line 87 of `src/Makefile` and remove `$(RM) -f $(STATICLIB)`.
My guess is that it was failing to remove `libstk.a` because it wasn't created yet.
Now I have `libstk.a`, which I can rename to `libstk.lib`.

I can list the contents of the lib:

lib /LIST libstk.lib
Microsoft (R) Library Manager Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Wurley.o
Whistle.o
Voicer.o
VoicForm.o
TwoZero.o
TwoPole.o
Twang.o
TubeBell.o
Stk.o
StifKarp.o
Sphere.o
Skini.o
Sitar.o
SingWave.o
SineWave.o
Simple.o
Shakers.o
Saxofony.o
Sampler.o
Rhodey.o
Resonate.o
Recorder.o
PoleZero.o
Plucked.o
PitShift.o
Phonemes.o
PercFlut.o
PRCRev.o
OneZero.o
OnePole.o
Noise.o
NRev.o
Moog.o
Modulate.o
ModalBar.o
Modal.o
MidiFileIn.o
Messager.o
Mesh2D.o
Mandolin.o
LentPitShift.o
JCRev.o
Iir.o
HevyMetl.o
Guitar.o
Granulate.o
FreeVerb.o
FormSwep.o
Flute.o
Fir.o
FileWvOut.o
FileWvIn.o
FileWrite.o
FileRead.o
FileLoop.o
FMVoices.o
FM.o
Envelope.o
Echo.o
Drummer.o
DelayL.o
DelayA.o
Delay.o
Clarinet.o
Chorus.o
Brass.o
Bowed.o
BlowHole.o
BlowBotl.o
BlitSquare.o
BlitSaw.o
Blit.o
BiQuad.o
BeeThree.o
BandedWG.o
Asymp.o
ADSR.o

Now I just need to get it working in my visual studio project, but I have unresolved external symbols
`1>CPlusPlusCHOPExample.obj : error LNK2001: unresolved external symbol "protected: static class stk::StkFrames stk::SineWave::table_" (?table_@SineWave@stk@@1VStkFrames@2@A)`

I thought I knew how to do this:
* Check C/C++>General>Additional Include Directories
  `../../stk/include;../../stk/src;../../stk/src/include`
* Check Linker>General>Additional Library Directories = `../../stk/src`
* Check Linker>General>Input. Make sure `libstk.lib` is included

I'm closing the issue because at least I have libstk.a.

**Comment by DBraun** [comment]
I'm trying to see if functions are exported correctly. `nm --demangle libstk.a > symbols.txt`
[symbols.txt](https://github.com/thestk/stk/files/4691255/dump.txt)

**Comment by radarsat1** [comment]
Unfortunately I'm almost sure you cannot just rename a `.a` produced by gcc to a `.lib` and use it with Visual Studio.  Even a DLL will probably give you problems since it won't use the same C++ runtime as Visual Studio, the only real solution is to compile STK itself using Visual Studio.

(aside, you can kind of do it for C, but for C++ i think it would get quite complicated: http://www.mingw.org/wiki/MSVC_and_MinGW_DLLs)

IF you really want to use libstk as a library in VS you might want to just import the whole thing into Visual Studio and provide the build flags (defines for OS and audio API, etc) through the project properties.  Otherwise you can also just copy individual parts of STK into your project.  A last possibility is to use CMake or similar to generate a Visual Studio project, but STK doesn't provide this.  If you're feeling adventurous you might be able to leverage the CMake files from [RtAudio](https://github.com/thestk/rtaudio) to create a Visual Studio project and then import STK into it.

**Comment by DBraun** [comment]
@radarsat1 Thanks for that info. I didn't know about the gcc nuance.

Your suggestion is exactly what I ended up doing last night. I made a project in my VS solution that compiles all the stk src to `.o` files. Then a post-build event links them into a lib: `lib /NOLOGO /OUT:"libstk.lib" "$(ProjectDir)\$(Platform)\$(Configuration)\*.obj"`. The other projects in the solution link against this lib, and luckily everything works! The .lib building project is also set as a dependency so that it builds first when necessary.

Thanks also for pointing out the CMake of RtAudio. I modified the vcxproj file of the .lib building project manually, but a CMake system would be more robust to changes in the stk source code.
