### ISSUE TITLE
Midi CCs can never Reach 1.0 when normalized via "ONE_OVER_128"-macro

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [thestk/stk#142]
Dear Mr. Scavone,
while trying to understand what it's all about the physical modeling synthesis I started studying you STK code and the first thing falling into my eyes is the "ONE_OVER_128" definition in stk.h.  It's used a lot to scale Midi integer inputs to floats, thus "ONE_OVER_128" is plain wrong, as the really reachable maximum value which should be accounted to as double{ 1.0 } is int{ 127 }.

It may even be the cause for some things "still sounding a bit off".

**Comment by garyscavone** [comment]
I think the ONE_OVER_128 scaling comes from Perry’s original STK code. And while it can be used to scale MIDI values for use in controlling parameter values of models, the actual range of values allowed in the controlChange() functions is from 0.0 to 128.0 (because the values passed are not necessarily coming from MIDI data). I don’t expect that this would be causing any significant sound issues.
