### ISSUE TITLE
RTAudio.cpp: 24 Bit input conversion to anything else produces erroneous output

### ISSUE THREAD

**Issue by aschneid1** [thestk/stk#65]
I just ran into this problem while working with a sound card that supports 24 bit inputs and below.  I was requesting RTAUDIO_FLOAT32 as my output format, but because my card only supported 24, 16, and 8 bit inputs, it defaulted to 24 bit.  The callback function for openStream was getting called twice as often as it should, and the internal stream time reflected that (i.e., the internal time thought 10 seconds had passed when only 5 had).   This was true no matter the target output format AFAICT, which makes me think the S24 class (defined in RTAudio.h) is broken.  For sure it was broken when my target output was Float 32.

I "fixed" this by commenting the code 

`deviceFormat = SND_PCM_FORMAT_S24;
   if ( snd_pcm_hw_params_test_format(phandle, hw_params, deviceFormat ) == 0 ) {
       stream_.deviceFormat[mode] = RTAUDIO_SINT24;
       goto setFormat;
   }
`

so the input format from the card was SND_PCM_FORMAT_S16 by default.  Perhaps the inJump/outJumps are miscalculated or there is a bug in the .asInt() method?

Edit - I should mentioned this was compiled for an Armv7 board in Little Endian.

**Comment by garyscavone** [comment]
It would be best if we could try to fix or figure out what is going on with your system, since I don�t have a linux system easily available, nor a 24-bit soundcard.

If you request FLOAT32 and your card (or API) doesn�t natively support that, then the convertBuffer() function should be invoked to convert between the two formats.  Now, I thought someone said recently that ALSA uses 4-byte words for 24-bit data? If that is the case, it might be interesting to try to override the FORMAT_S24 with an S32 format.  And if that is the case, the question remains whether they use the upper or lower 3 bytes to hold the data.

**Comment by garyscavone** [comment]
I have to find some documentation on how the ALSA API supports 24-bit data. But the implication from a previous email was that the ALSA driver might pass 24-bit data from the soundcard to the user in a 32-bit data format.

**Comment by garyscavone** [comment]
I just did some checking and there is a related Issue on the RtAudio site.

I suggest changing line 7135 in RtAudio.cpp from

    info.nativeFormats |= RTAUDIO_SINT24;

to

    info.nativeFormats |= RTAUDIO_SINT32;

and see what happens when you request 32-bit data.  The ALSA documentation says that 24-bit data uses the lower 3 bytes of a 32-bit int. If that works, there will still likely be a scaling problem but then we can look into fixing that.

Regards,

—gary

**Comment by garyscavone** [comment]
This is old and if still a problem should be posted to the RtAudio github site.
